apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: sv53gjt87-go
  janus-idp.io/tekton: sv53gjt87-go
  backstage.io/kubernetes-id: sv53gjt87-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: sv53gjt87-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
